name: Deploy to EC2.

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve secret repository
        env: # Set the secret as an input
          EC2_PRIVATE_KEY_BASE64: ${{ secrets.EC2_PRIVATE_KEY_BASE64 }}
          TEST: This is a test
          EC2_HOST: ${{ vars.EC2_HOST }}

        uses: actions/checkout@v2
      - name: see secrets
        run: echo "${{ secrets.EC2_PRIVATE_KEY_BASE64 }}"
      - name: see unset secrets
        run: echo "${{ secrets.EC2_PRIVATE_KEY_BASE64_ }}"
      - name: see variables
        run: echo "${{ vars.EC2_PRIVATE_KEY_BASE64 }}"
      - name: see unset variables
        run: echo "${{ vars.EC2_PRIVATE_KEY_BASE64_ }}"
      - name: see secrets
        run: echo "${{ secrets.EC2_PRIVATE_KEY_BASE64 }}"
      - name: see EC2_HOST
        run: echo "$EC2_HOST"
      - name: see EC2_HOST
        run: echo " ${{ vars.EC2_HOST }}"
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "Printing test: "
          echo "$TEST"
          # echo "${{ secrets.EC2_PRIVATE_KEY_BASE64 }}" | base64 --decode > ~/sao_paulo.pem
          echo "teste-teste-teste" > ~/sao_paulo.pem
          du -h ~/sao_paulo.pem
          chmod 600 ~/sao_paulo.pem
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo ~/sao_paulo.pem
          ping ${{ vars.EC2_HOST }}
