name: Deploy to EC2.

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        env: # Set the secret as an input
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          TEST: This is a test
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$TEST"
          echo "$EC2_SSH_PUBLIC_KEY" > ~/.ssh/authorized_keys
          echo "$EC2_SSH_PRIVATE_KEY" > ~/sao_paulo.pem
          du -h ~/sao_paulo.pem
          chmod 600 ~/sao_paulo.pem
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Connect to EC2 instance
        run: |
          echo "52.67.200.54"
          ssh -o StrictHostKeyChecking=no -v -i ~/sao_paulo.pem ec2-user@52.67.200.54 << 'EOF'
            # Commands to run on the EC2 instance
            echo "Connected to EC2 instance!"
            touch ~/new-file.txt
            # You can add more commands here
          EOF
