name: Deploy to EC2.

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve secret repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY_BASE64 }}" | base64 --decode > ~/sao_paulo.pem
          du -h ~/sao_paulo.pem
          chmod 600 ~/sao_paulo.pem
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo ~/sao_paulo.pem

      - name: Connect to EC2 instance
        run: |
          echo "connecting to ${{ vars.EC2_HOST }}"
          ssh -o StrictHostKeyChecking=no -v -i ~/sao_paulo.pem ec2-user@52.67.200.54 << 'EOF'
            # Commands to run on the EC2 instance
            echo "Connected to EC2 instance!"
            touch ~/new-file.txt
            # You can add more commands here
          EOF
